# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
                ('opposite_color', models.CharField(max_length=6)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('stop_id', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.Route')),
            ],
        ),
    ]
