# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20151215_load_routes_and_stops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['tag']},
        ),
        migrations.AddField(
            model_name='route',
            name='monitored',
            field=models.BooleanField(default=False),
        ),
    ]
