# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Direction')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Stop')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='stops',
            field=models.ManyToManyField(through='routes.DirectionStop', to='routes.Stop'),
        ),
    ]
