# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.Direction'),
        ),
    ]
